version: '3'
services:
  db:
    image: mysql:latest
    
    environment:
      MYSQL_ROOT_PASSWORD: agenda
      MYSQL_DATABASE: agenda
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - 3306:3306
